# Generated by Django 3.0 on 2021-08-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='creator',
        ),
    ]
