# Generated by Django 3.0 on 2021-08-19 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_auto_20210817_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(related_name='product_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
