# Generated by Django 3.0 on 2021-08-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='userz',
            new_name='user',
        ),
    ]
